package view;

import java.sql.SQLException;
import java.util.List;
import java.util.Map;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import exception.SaldoInsuficienteException;
import model.ContaCorrente;
import service.ContaService;
import strategy.TarifaStrategy;

public class ContasGUI extends javax.swing.JFrame {
    private ContaService cs = new ContaService();
    private ContaCorrente conta;
    
    private void carregarConta(){
        try {
            cs.carregarContasDoBanco();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(
                    this,
                    "Erro ao carregar as contas: " + e.getMessage(),
                    "Erro",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }
    
    private void carregarTabela(){
        Map<Integer, ContaCorrente> contas = cs.getContas();
        
        DefaultTableModel modelo =
                (DefaultTableModel) tblContas.getModel();
        
        for(ContaCorrente conta : contas.values()){
            modelo.addRow(new Object[]{
                conta.getNumero(),
                conta.getTitular(),
                conta.getSaldo()
            });
        }
    }
    
    public void adicionarContaNaTabela(ContaCorrente conta){
        DefaultTableModel modelo =
            (DefaultTableModel) tblContas.getModel();
        
        modelo.addRow(new Object[]{
            conta.getNumero(),
            conta.getTitular(),
            conta.getSaldo()
        });
    }
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ContasGUI.class.getName());

    /**
     * Creates new form ContaGUI
     */
    public ContasGUI() {
        initComponents();
        carregarConta();
        carregarTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lblTitulo = new javax.swing.JLabel();
        lblNumero = new javax.swing.JLabel();
        lblTitular = new javax.swing.JLabel();
        lblSaldo = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        txtTitular = new javax.swing.JTextField();
        txtSaldo = new javax.swing.JTextField();
        lblValorSaque = new javax.swing.JLabel();
        txtValorSaque = new javax.swing.JTextField();
        btnSacar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblContas = new javax.swing.JTable();
        lvlValorDeposito = new javax.swing.JLabel();
        txtValorDeposito = new javax.swing.JTextField();
        btnDepositar = new javax.swing.JButton();
        btnAdicionarConta = new javax.swing.JButton();
        btnFiltrarSaldo = new javax.swing.JButton();
        btnSaldoTotal = new javax.swing.JButton();
        btnAgruparSaldo = new javax.swing.JButton();
        btnFiltrarPar = new javax.swing.JButton();
        btnOrdenarSaldo = new javax.swing.JButton();
        btnOrdenarTitular = new javax.swing.JButton();
        cmbTarifa = new javax.swing.JComboBox<>();
        btnCalcularTarifa = new javax.swing.JButton();
        btnExcluirConta = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Gerenciador de Contas Bancárias");

        lblNumero.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblNumero.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblNumero.setText("Número:");

        lblTitular.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblTitular.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTitular.setText("Titular:");

        lblSaldo.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblSaldo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblSaldo.setText("Saldo disponível:");

        txtNumero.setEditable(false);

        txtTitular.setEditable(false);

        txtSaldo.setEditable(false);

        lblValorSaque.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblValorSaque.setText("Valor para Saque:");

        btnSacar.setBackground(new java.awt.Color(255, 255, 153));
        btnSacar.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        btnSacar.setForeground(new java.awt.Color(102, 102, 0));
        btnSacar.setText("Sacar");
        btnSacar.addActionListener(this::btnSacarActionPerformed);

        tblContas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Número", "Titular", "Saldo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblContas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblContasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblContas);

        lvlValorDeposito.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lvlValorDeposito.setText("Valor para depósito:");

        btnDepositar.setBackground(new java.awt.Color(204, 255, 153));
        btnDepositar.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        btnDepositar.setForeground(new java.awt.Color(102, 102, 0));
        btnDepositar.setText("Depositar");
        btnDepositar.addActionListener(this::btnDepositarActionPerformed);

        btnAdicionarConta.setBackground(new java.awt.Color(102, 204, 255));
        btnAdicionarConta.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnAdicionarConta.setForeground(new java.awt.Color(0, 0, 0));
        btnAdicionarConta.setText("Adicionar conta");
        btnAdicionarConta.addActionListener(this::btnAdicionarContaActionPerformed);

        btnFiltrarSaldo.setBackground(new java.awt.Color(255, 204, 204));
        btnFiltrarSaldo.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        btnFiltrarSaldo.setForeground(new java.awt.Color(51, 51, 51));
        btnFiltrarSaldo.setText("Filtrar Maior Que 5mil");
        btnFiltrarSaldo.addActionListener(this::btnFiltrarSaldoActionPerformed);

        btnSaldoTotal.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        btnSaldoTotal.setText("Calcular Saldo Total");
        btnSaldoTotal.addActionListener(this::btnSaldoTotalActionPerformed);

        btnAgruparSaldo.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        btnAgruparSaldo.setText("Agrupar por Saldo");
        btnAgruparSaldo.addActionListener(this::btnAgruparSaldoActionPerformed);

        btnFiltrarPar.setBackground(new java.awt.Color(255, 204, 204));
        btnFiltrarPar.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        btnFiltrarPar.setForeground(new java.awt.Color(51, 51, 51));
        btnFiltrarPar.setText("Filtrar Contas Pares");
        btnFiltrarPar.addActionListener(this::btnFiltrarParActionPerformed);

        btnOrdenarSaldo.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        btnOrdenarSaldo.setText("Ordenar por Saldo");
        btnOrdenarSaldo.addActionListener(this::btnOrdenarSaldoActionPerformed);

        btnOrdenarTitular.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        btnOrdenarTitular.setText("Ordenar por Titular");
        btnOrdenarTitular.addActionListener(this::btnOrdenarTitularActionPerformed);

        cmbTarifa.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        cmbTarifa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FIXA", "PERCENTUAL", "ISENTA" }));

        btnCalcularTarifa.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        btnCalcularTarifa.setText("Calcular Tarifa");
        btnCalcularTarifa.addActionListener(this::btnCalcularTarifaActionPerformed);

        btnExcluirConta.setBackground(new java.awt.Color(255, 102, 102));
        btnExcluirConta.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnExcluirConta.setForeground(new java.awt.Color(0, 0, 0));
        btnExcluirConta.setText("Excluir Conta");
        btnExcluirConta.addActionListener(this::btnExcluirContaActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(btnFiltrarSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnFiltrarPar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(btnOrdenarSaldo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnOrdenarTitular, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnAgruparSaldo, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                    .addComponent(btnSaldoTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                    .addComponent(cmbTarifa, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnCalcularTarifa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTitular, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSaldo)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnDepositar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSacar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtValorDeposito, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtValorSaque, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lvlValorDeposito, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnExcluirConta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblValorSaque, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTitular, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnAdicionarConta, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNumero)
                            .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTitular)
                            .addComponent(txtTitular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSaldo)
                            .addComponent(txtSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAdicionarConta)
                            .addComponent(btnExcluirConta))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnFiltrarSaldo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFiltrarPar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAgruparSaldo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSaldoTotal))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lvlValorDeposito)
                        .addComponent(lblValorSaque)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOrdenarSaldo)
                    .addComponent(cmbTarifa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValorDeposito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValorSaque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOrdenarTitular)
                    .addComponent(btnCalcularTarifa)
                    .addComponent(btnDepositar)
                    .addComponent(btnSacar))
                .addGap(0, 22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSacarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacarActionPerformed
        if (conta == null) {
            JOptionPane.showMessageDialog(
                    this,
                    "Selecione uma conta para realizar o saque.",
                    "Aviso",
                    JOptionPane.WARNING_MESSAGE
            );
            return;
        }
        
        try {
            double valor = Double.parseDouble(txtValorSaque.getText());
            
            cs.sacarValor(conta, valor);
            
            txtSaldo.setText(String.format("%.2f", conta.getSaldo()));
            txtValorSaque.setText("");
            
            int linha = tblContas.getSelectedRow();
            tblContas.setValueAt(conta.getSaldo(), linha, 2);
            
            JOptionPane.showMessageDialog(
                    this,
                    "Saque realizado com sucesso!"
            );
        } catch (SaldoInsuficienteException e) {
            JOptionPane.showMessageDialog(
                    this,
                    e.getMessage(),
                    "Erro",
                    JOptionPane.ERROR_MESSAGE
            );
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(
                    this,
                    "Insira um valor valido.",
                    "Erro",
                    JOptionPane.ERROR_MESSAGE
            );
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(
                    this,
                    "Erro ao atualizar o saldo: " + e.getMessage(),
                    "Erro",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_btnSacarActionPerformed

    private void tblContasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblContasMouseClicked
        int linha = tblContas.getSelectedRow();
        int numero = (int) tblContas.getValueAt(linha, 0);
        conta = cs.getContas().get(numero);
        
        txtNumero.setText(String.valueOf(conta.getNumero()));
        txtTitular.setText(conta.getTitular());
        txtSaldo.setText(String.format("%.2f", conta.getSaldo()));
    }//GEN-LAST:event_tblContasMouseClicked

    private void btnDepositarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepositarActionPerformed
        if (conta == null) {
            JOptionPane.showMessageDialog(
                    this,
                    "Selecione uma conta para realizar o depósito.",
                    "Aviso",
                    JOptionPane.WARNING_MESSAGE
            );
            return;
        }
        
        try {
            double valor = Double.parseDouble(txtValorDeposito.getText());

            cs.depositarValor(conta, valor);

            txtSaldo.setText(String.format("%.2f", conta.getSaldo()));
            
            txtValorDeposito.setText("");

            int linha = tblContas.getSelectedRow();
            
            tblContas.setValueAt(conta.getSaldo(), linha, 2);

            JOptionPane.showMessageDialog(
                    this,
                    "Depósito realizado com sucesso!"
            );
        } catch (SaldoInsuficienteException e) {
            JOptionPane.showMessageDialog(
                    this,
                    e.getMessage(),
                    "Erro",
                    JOptionPane.ERROR_MESSAGE
            );
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(
                    this,
                    "Insira um valor válido.",
                    "Erro",
                    JOptionPane.ERROR_MESSAGE
            );
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(
                    this,
                    "Erro ao atualizar o saldo: " + e.getMessage(),
                    "Erro",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_btnDepositarActionPerformed

    private void btnAdicionarContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarContaActionPerformed
        new AdicionarContaGUI(cs, this).setVisible(true);
    }//GEN-LAST:event_btnAdicionarContaActionPerformed

    private void btnFiltrarSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarSaldoActionPerformed
        List<ContaCorrente> contasFiltradas = cs.filtrarPorSaldo();
        
        DefaultTableModel modelo = (DefaultTableModel) tblContas.getModel();
        modelo.setRowCount(0);
        
        for(ContaCorrente conta : contasFiltradas){
            modelo.addRow(new Object[]{
                conta.getNumero(),
                conta.getTitular(),
                conta.getSaldo()
            });
        }
    }//GEN-LAST:event_btnFiltrarSaldoActionPerformed

    private void btnSaldoTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaldoTotalActionPerformed
        double saldoTotal = cs.calcularSaldoTotal();
        
        JOptionPane.showMessageDialog(
                this,
                "Saldo total: R$ " + String.format("%.2f", saldoTotal)
        );
    }//GEN-LAST:event_btnSaldoTotalActionPerformed

    private void btnAgruparSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgruparSaldoActionPerformed
        Map<String, List<ContaCorrente>> grupos = cs.agruparPorSaldo();
        
        StringBuilder texto = new StringBuilder();
        
        List<ContaCorrente> contasAte5000 = grupos.get("Até R$5.000");
        List<ContaCorrente> contas5001A10000 = grupos.get("R$5.001 a R$10.000");
        List<ContaCorrente> contasAcima10000 = grupos.get("Acima de R$10.000");
        
        texto.append("Até R$5.000:\n");
        for(ContaCorrente conta : contasAte5000){
                texto.append(conta.getNumero())
                     .append(". ")
                     .append(conta.getTitular())
                     .append(" - R$")
                     .append(String.format("%.2f", conta.getSaldo()))
                     .append("\n");
        }
        
        texto.append("\nR$5.001 a R$10.000:\n");
        for(ContaCorrente conta : contas5001A10000){
                texto.append(conta.getNumero())
                     .append(". ")
                     .append(conta.getTitular())
                     .append(" - R$")
                     .append(String.format("%.2f", conta.getSaldo()))
                     .append("\n");
        }
        
        texto.append("\nAcima de R$10.000:\n");
        for(ContaCorrente conta : contasAcima10000){
                texto.append(conta.getNumero())
                     .append(". ")
                     .append(conta.getTitular())
                     .append(" - R$")
                     .append(String.format("%.2f", conta.getSaldo()))
                     .append("\n");
        }
        
        JOptionPane.showMessageDialog(
                this,
                texto.toString(),
                "Contas agrupadas por saldo",
                JOptionPane.INFORMATION_MESSAGE
        );
    }//GEN-LAST:event_btnAgruparSaldoActionPerformed

    private void btnFiltrarParActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarParActionPerformed
        List<ContaCorrente> contasFiltradas = cs.filtrarContasPar();
        
        DefaultTableModel modelo = (DefaultTableModel) tblContas.getModel();
        modelo.setRowCount(0);
        
        for(ContaCorrente conta : contasFiltradas){
            modelo.addRow(new Object[]{
                conta.getNumero(),
                conta.getTitular(),
                conta.getSaldo()
            });
        }
    }//GEN-LAST:event_btnFiltrarParActionPerformed

    private void btnOrdenarSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdenarSaldoActionPerformed
        List<ContaCorrente> contasOrdenadas = cs.ordenarPorSaldo();
        
        DefaultTableModel modelo = (DefaultTableModel) tblContas.getModel();
        modelo.setRowCount(0);
        
        for(ContaCorrente conta : contasOrdenadas){
            modelo.addRow(new Object[]{
                conta.getNumero(),
                conta.getTitular(),
                conta.getSaldo()
            });
        }
    }//GEN-LAST:event_btnOrdenarSaldoActionPerformed

    private void btnOrdenarTitularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdenarTitularActionPerformed
        List<ContaCorrente> contasOrdenadas = cs.ordenarPorTitular();
        
        DefaultTableModel modelo = (DefaultTableModel) tblContas.getModel();
        modelo.setRowCount(0);
        
        for(ContaCorrente conta : contasOrdenadas){
            modelo.addRow(new Object[]{
                conta.getNumero(),
                conta.getTitular(),
                conta.getSaldo()
            });
        }
    }//GEN-LAST:event_btnOrdenarTitularActionPerformed

    private void btnCalcularTarifaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularTarifaActionPerformed
        int linhaSelecionada = tblContas.getSelectedRow();
        
        if(linhaSelecionada == -1){
            JOptionPane.showMessageDialog(this, "Selecione uma conta.");
            return;
        }
        
        int numeroConta = (int) tblContas.getValueAt(linhaSelecionada, 0);
        ContaCorrente contaSelecionada = cs.getContas().get(numeroConta);
        
        TarifaStrategy estrategia = TarifaStrategy.valueOf(
                cmbTarifa.getSelectedItem().toString()
        );
        
        double tarifa = contaSelecionada.calcularTarifa(estrategia);
        
        JOptionPane.showMessageDialog(
                this,
                String.format("Tarifa: R$%.2f", tarifa)
        );
    }//GEN-LAST:event_btnCalcularTarifaActionPerformed

    private void btnExcluirContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirContaActionPerformed
        if (conta == null) {
            JOptionPane.showMessageDialog(
                    this,
                    "Selecione uma conta para excluir.",
                    "Aviso",
                    JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        int confirmacao = JOptionPane.showConfirmDialog(
                this,
                "Deseja realmente excluir esta conta?",
                "Confirmar exclusão",
                JOptionPane.YES_NO_OPTION
        );

        if (confirmacao != JOptionPane.YES_OPTION) {
            return;
        }

        try {
            cs.removerConta(conta.getNumero());

            int linha = tblContas.getSelectedRow();
            
            DefaultTableModel modelo = (DefaultTableModel) tblContas.getModel();

            modelo.removeRow(linha);

            conta = null;

            txtNumero.setText("");
            txtTitular.setText("");
            txtSaldo.setText("");

            JOptionPane.showMessageDialog(
                    this,
                    "Conta excluída com sucesso!"
            );

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(
                    this,
                    "Erro ao excluir a conta: " + e.getMessage(),
                    "Erro",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_btnExcluirContaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ContasGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionarConta;
    private javax.swing.JButton btnAgruparSaldo;
    private javax.swing.JButton btnCalcularTarifa;
    private javax.swing.JButton btnDepositar;
    private javax.swing.JButton btnExcluirConta;
    private javax.swing.JButton btnFiltrarPar;
    private javax.swing.JButton btnFiltrarSaldo;
    private javax.swing.JButton btnOrdenarSaldo;
    private javax.swing.JButton btnOrdenarTitular;
    private javax.swing.JButton btnSacar;
    private javax.swing.JButton btnSaldoTotal;
    private javax.swing.JComboBox<String> cmbTarifa;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JLabel lblSaldo;
    private javax.swing.JLabel lblTitular;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblValorSaque;
    private javax.swing.JLabel lvlValorDeposito;
    private javax.swing.JTable tblContas;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtSaldo;
    private javax.swing.JTextField txtTitular;
    private javax.swing.JTextField txtValorDeposito;
    private javax.swing.JTextField txtValorSaque;
    // End of variables declaration//GEN-END:variables
}
