package view;

import java.io.IOException;
import java.util.List;
import java.util.Map;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import exception.SaldoInsuficienteException;
import model.ContaCorrente;
import service.ContaService;

public class ContasGUI extends javax.swing.JFrame {
    private ContaService cs = new ContaService();
    private ContaCorrente conta;
    
    private void carregarConta(){
        try {
            cs.lerContas("contas.txt");
        } catch (IOException e) {
            JOptionPane.showMessageDialog(
                    this,
                    "Erro ao carregar as contas: " + e.getMessage(),
                    "Erro",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }
    
    private void carregarTabela(){
        Map<Integer, ContaCorrente> contas = cs.getContas();
        
        javax.swing.table.DefaultTableModel modelo =
                (javax.swing.table.DefaultTableModel) tblContas.getModel();
        
        for (ContaCorrente conta : contas.values()) {
            modelo.addRow(new Object[]{
                conta.getNumero(),
                conta.getTitular(),
                conta.getSaldo()
            });
        }
    }
    
    public void adicionarContaNaTabela(ContaCorrente conta){
        DefaultTableModel modelo =
            (DefaultTableModel) tblContas.getModel();
        
        modelo.addRow(new Object[]{
            conta.getNumero(),
            conta.getTitular(),
            conta.getSaldo()
        });
    }
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ContasGUI.class.getName());

    /**
     * Creates new form ContaGUI
     */
    public ContasGUI() {
        initComponents();
        carregarConta();
        carregarTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lblTitulo = new javax.swing.JLabel();
        lblNumero = new javax.swing.JLabel();
        lblTitular = new javax.swing.JLabel();
        lblSaldo = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        txtTitular = new javax.swing.JTextField();
        txtSaldo = new javax.swing.JTextField();
        lblValorSaque = new javax.swing.JLabel();
        txtValorSaque = new javax.swing.JTextField();
        btnSacar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblContas = new javax.swing.JTable();
        lvlValorDeposito = new javax.swing.JLabel();
        txtValorDeposito = new javax.swing.JTextField();
        btnDepositar = new javax.swing.JButton();
        btnAdicionarConta = new javax.swing.JButton();
        btnFiltrarSaldo = new javax.swing.JButton();
        btnSaldoTotal = new javax.swing.JButton();
        btnAgruparSaldo = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Gerenciador de Contas Bancárias");

        lblNumero.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNumero.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblNumero.setText("Número:");

        lblTitular.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTitular.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTitular.setText("Titular:");

        lblSaldo.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblSaldo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblSaldo.setText("Saldo disponível:");

        txtNumero.setEditable(false);

        txtTitular.setEditable(false);

        txtSaldo.setEditable(false);

        lblValorSaque.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblValorSaque.setText("Valor para Saque:");

        btnSacar.setBackground(new java.awt.Color(255, 255, 153));
        btnSacar.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        btnSacar.setForeground(new java.awt.Color(102, 102, 0));
        btnSacar.setText("Sacar");
        btnSacar.addActionListener(this::btnSacarActionPerformed);

        tblContas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Número", "Titular", "Saldo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblContas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblContasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblContas);

        lvlValorDeposito.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lvlValorDeposito.setText("Valor para depósito:");

        btnDepositar.setBackground(new java.awt.Color(204, 255, 153));
        btnDepositar.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        btnDepositar.setForeground(new java.awt.Color(102, 102, 0));
        btnDepositar.setText("Depositar");
        btnDepositar.addActionListener(this::btnDepositarActionPerformed);

        btnAdicionarConta.setBackground(new java.awt.Color(153, 204, 255));
        btnAdicionarConta.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        btnAdicionarConta.setForeground(new java.awt.Color(0, 102, 102));
        btnAdicionarConta.setText("Adicionar conta");
        btnAdicionarConta.addActionListener(this::btnAdicionarContaActionPerformed);

        btnFiltrarSaldo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnFiltrarSaldo.setText("Filtrar Maior Que 10mil");
        btnFiltrarSaldo.addActionListener(this::btnFiltrarSaldoActionPerformed);

        btnSaldoTotal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSaldoTotal.setText("Calcular Saldo Total");
        btnSaldoTotal.addActionListener(this::btnSaldoTotalActionPerformed);

        btnAgruparSaldo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAgruparSaldo.setText("Agrupar por Saldo");
        btnAgruparSaldo.addActionListener(this::btnAgruparSaldoActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnFiltrarSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAdicionarConta, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lvlValorDeposito, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblValorSaque, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(6, 6, 6))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtValorDeposito, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(btnDepositar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSacar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtValorSaque, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSaldoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAgruparSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lblNumero, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblTitular, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblSaldo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtTitular)
                                    .addComponent(txtNumero, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                                    .addComponent(txtSaldo))))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFiltrarSaldo)
                    .addComponent(btnAdicionarConta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSaldoTotal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAgruparSaldo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumero)
                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitular)
                    .addComponent(txtTitular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSaldo)
                    .addComponent(txtSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lvlValorDeposito)
                    .addComponent(lblValorSaque))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtValorDeposito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValorSaque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDepositar)
                    .addComponent(btnSacar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSacarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacarActionPerformed
        if(conta == null) {
            JOptionPane.showMessageDialog(
                    this,
                    "Selecione uma conta para realizar o saque.",
                    "Aviso",
                    JOptionPane.WARNING_MESSAGE
            );
            return;
        }
        
        try {
            double valor = Double.parseDouble(txtValorSaque.getText());
            
            cs.sacarValor(conta, valor);
            
            txtSaldo.setText(String.format("%.2f", conta.getSaldo()));
            txtValorSaque.setText("");
            
            int linha = tblContas.getSelectedRow();
            tblContas.setValueAt(conta.getSaldo(), linha, 2);
            
            cs.atualizarContas("contas.txt");
            
            JOptionPane.showMessageDialog(
                    this,
                    "Saque realizado com sucesso!"
            );
        } catch (SaldoInsuficienteException e) {
            JOptionPane.showMessageDialog(
                    this,
                    e.getMessage(),
                    "Erro",
                    JOptionPane.ERROR_MESSAGE
            );
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(
                    this,
                    "Insira um valor valido.",
                    "Erro",
                    JOptionPane.ERROR_MESSAGE
            );
        } catch (IOException e) {
            JOptionPane.showMessageDialog(
                    this,
                    "Erro ao salvar a conta: " + e.getMessage(),
                    "Erro",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_btnSacarActionPerformed

    private void tblContasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblContasMouseClicked
        int linha = tblContas.getSelectedRow();
        int numero = (int) tblContas.getValueAt(linha, 0);
        conta = cs.getContas().get(numero);
        
        txtNumero.setText(String.valueOf(conta.getNumero()));
        txtTitular.setText(conta.getTitular());
        txtSaldo.setText(String.format("%.2f", conta.getSaldo()));
    }//GEN-LAST:event_tblContasMouseClicked

    private void btnDepositarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepositarActionPerformed
        if(conta == null){
            JOptionPane.showMessageDialog(
                    this,
                    "Selecione uma conta para realizar o depósito.",
                    "Aviso",
                    JOptionPane.WARNING_MESSAGE
            );
            return;
        }
        
        try {
            double valor = Double.parseDouble(txtValorDeposito.getText());

            conta.depositar(valor);

            txtSaldo.setText(String.format("%.2f", conta.getSaldo()));
            txtValorDeposito.setText("");

            int linha = tblContas.getSelectedRow();
            tblContas.setValueAt(conta.getSaldo(), linha, 2);

            cs.atualizarContas("contas.txt");

            JOptionPane.showMessageDialog(
                    this,
                    "Depósito realizado com sucesso!"
            );
        } catch (SaldoInsuficienteException e) {
            JOptionPane.showMessageDialog(
                    this,
                    e.getMessage(),
                    "Erro",
                    JOptionPane.ERROR_MESSAGE
            );
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(
                    this,
                    "Insira um valor válido.",
                    "Erro",
                    JOptionPane.ERROR_MESSAGE
            );
        } catch (IOException e) {
            JOptionPane.showMessageDialog(
                    this,
                    "Erro ao salvar a conta: " + e.getMessage(),
                    "Erro",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_btnDepositarActionPerformed

    private void btnAdicionarContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarContaActionPerformed
        new AdicionarContaGUI(cs, this).setVisible(true);
    }//GEN-LAST:event_btnAdicionarContaActionPerformed

    private void btnFiltrarSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarSaldoActionPerformed
        List<ContaCorrente> contasFiltradas = cs.filtrarContasSaldoAlto();
        
        DefaultTableModel modelo = (DefaultTableModel) tblContas.getModel();
        
        modelo.setRowCount(0);
        
        for(ContaCorrente conta : contasFiltradas){
            modelo.addRow(new Object[]{
                conta.getNumero(),
                conta.getTitular(),
                conta.getSaldo()
            });
        }
    }//GEN-LAST:event_btnFiltrarSaldoActionPerformed

    private void btnSaldoTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaldoTotalActionPerformed
        double saldoTotal = cs.calcularSaldoTotal();
        
        JOptionPane.showMessageDialog(
                this,
                "Saldo total: R$ " + String.format("%.2f", saldoTotal)
        );
    }//GEN-LAST:event_btnSaldoTotalActionPerformed

    private void btnAgruparSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgruparSaldoActionPerformed
        Map<String, List<ContaCorrente>> grupos = cs.agruparPorSaldo();
        
        StringBuilder texto = new StringBuilder();
        
        List<ContaCorrente> contasAte5000 = grupos.get("Até R$5.000");
        List<ContaCorrente> contas5001A10000 = grupos.get("R$5.001 a R$10.000");
        List<ContaCorrente> contasAcima10000 = grupos.get("Acima de R$10.000");
        
        texto.append("Até R$5.000:\n");
        for(ContaCorrente conta : contasAte5000){
                texto.append(conta.getNumero())
                     .append(". ")
                     .append(conta.getTitular())
                     .append(" - R$")
                     .append(String.format("%.2f", conta.getSaldo()))
                     .append("\n");
        }
        
        texto.append("\nR$5.001 a R$10.000:\n");
        for(ContaCorrente conta : contas5001A10000){
                texto.append(conta.getNumero())
                     .append(". ")
                     .append(conta.getTitular())
                     .append(" - R$")
                     .append(String.format("%.2f", conta.getSaldo()))
                     .append("\n");
        }
        
        texto.append("\nAcima de R$10.000:\n");
        for(ContaCorrente conta : contasAcima10000){
                texto.append(conta.getNumero())
                     .append(". ")
                     .append(conta.getTitular())
                     .append(" - R$")
                     .append(String.format("%.2f", conta.getSaldo()))
                     .append("\n");
        }
        
        JOptionPane.showMessageDialog(
                this,
                texto.toString(),
                "Contas agrupadas por saldo",
                JOptionPane.INFORMATION_MESSAGE
        );
    }//GEN-LAST:event_btnAgruparSaldoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ContasGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionarConta;
    private javax.swing.JButton btnAgruparSaldo;
    private javax.swing.JButton btnDepositar;
    private javax.swing.JButton btnFiltrarSaldo;
    private javax.swing.JButton btnSacar;
    private javax.swing.JButton btnSaldoTotal;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JLabel lblSaldo;
    private javax.swing.JLabel lblTitular;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblValorSaque;
    private javax.swing.JLabel lvlValorDeposito;
    private javax.swing.JTable tblContas;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtSaldo;
    private javax.swing.JTextField txtTitular;
    private javax.swing.JTextField txtValorDeposito;
    private javax.swing.JTextField txtValorSaque;
    // End of variables declaration//GEN-END:variables
}
